openapi: "3.0.0"
info:
  x-audience: who-cares
  version: 1.0.0
  title: API Title
  license:
    name: GNU
paths:
  /pet:
    patch:
      description: update a pet
      operationId: update-pet
      tags: [foo]
      responses:
        '200':
          description: ok
          content: {}
        '500':
          description: server error
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'